export const FINANCEIRO_STATUS = {
    RASCUNHO: 'RASCUNHO',
    PAGO: 'PAGO',
} as const;

export const LANCAMENTO_TIPO = {
    ENTRADA: 'ENTRADA',
    SAIDA: 'SAIDA',
} as const;

export const PIX_TYPES = {
    CPF: 'CPF',
    CNPJ: 'CNPJ',
    EMAIL: 'EMAIL',
    TELEFONE: 'TELEFONE',
    ALEATORIA: 'ALEATORIA',
} as const;

export type PixType = keyof typeof PIX_TYPES;

export const CALENDARIO_STATUS = {
    TRABALHADO: 'TRABALHADO',
    SEM_ATIVIDADE: 'SEM_ATIVIDADE',
    NAO_VIGENTE: 'NAO_VIGENTE',
    FUTURO: 'FUTURO',
    FERIADO: 'FERIADO',
} as const;

export const STATUS_FATURA = {
    EM_MEDICAO: 'EM_MEDICAO',
    AGUARDANDO_APROVACAO: 'AGUARDANDO_APROVACAO',
    EMITIDA_PENDENTE: 'EMITIDA_PENDENTE',
    PAGO_PARCIAL: 'PAGO_PARCIAL',
    LIQUIDADA: 'LIQUIDADA',
    CANCELADA: 'CANCELADA',
} as const;

export type StatusFaturaType = typeof STATUS_FATURA[keyof typeof STATUS_FATURA];

export const STATUS_INTERCOMPANY = {
    PENDENTE_ACERTO: 'PENDENTE_ACERTO',
    COMPENSADO: 'COMPENSADO',
} as const;

export type StatusIntercompanyType = typeof STATUS_INTERCOMPANY[keyof typeof STATUS_INTERCOMPANY];

export const TIPO_COBRANCA_CLIENTE = {
    DIARIA_MOTOBOY: 'DIARIA_MOTOBOY',
    FIXO_MENSAL: 'FIXO_MENSAL',
    PRODUCAO_ENTREGA: 'PRODUCAO_ENTREGA',
} as const;

export type TipoCobrancaClienteType = typeof TIPO_COBRANCA_CLIENTE[keyof typeof TIPO_COBRANCA_CLIENTE];

export const CATEGORIA_DESPESA = {
    DESPESA_FIXA: 'DESPESA_FIXA',
    TRIBUTO_DAS: 'TRIBUTO_DAS',
    PARCELAMENTO_FISCAL: 'PARCELAMENTO_FISCAL',
    INVESTIMENTO_FINANCIAMENTO: 'INVESTIMENTO_FINANCIAMENTO',
    DESPESA_FINANCEIRA: 'DESPESA_FINANCEIRA',
    PROLABORE: 'PROLABORE',
    INVESTIMENTO_PATRIMONIAL: 'INVESTIMENTO_PATRIMONIAL',
    CARTAO_CREDITO: 'CARTAO_CREDITO',
    DESPESA_ADMINISTRATIVA: 'DESPESA_ADMINISTRATIVA',
    DESPESA_FROTA_DOCUMENTO: 'DESPESA_FROTA_DOCUMENTO',
} as const;

export type CategoriaDespesaType = typeof CATEGORIA_DESPESA[keyof typeof CATEGORIA_DESPESA];

export const STATUS_DESPESA = {
    PENDENTE: 'PENDENTE',
    ADIADA: 'ADIADA',
    PAGO: 'PAGO',
    CANCELADO: 'CANCELADO',
} as const;

export type StatusDespesaType = typeof STATUS_DESPESA[keyof typeof STATUS_DESPESA];

export const TIPO_MOVIMENTACAO_AVULSA = {
    ENTRADA: 'ENTRADA',
    SAIDA: 'SAIDA',
} as const;

export type TipoMovimentacaoAvulsaType = typeof TIPO_MOVIMENTACAO_AVULSA[keyof typeof TIPO_MOVIMENTACAO_AVULSA];

export const CATEGORIA_MOVIMENTACAO_AVULSA = {
    CLIENTE_A_VISTA: 'CLIENTE_A_VISTA',
    RENDIMENTO_APLICACAO: 'RENDIMENTO_APLICACAO',
    REEMBOLSO: 'REEMBOLSO',
    OUTRAS_RECEITAS: 'OUTRAS_RECEITAS',
    OUTRAS_DESPESAS: 'OUTRAS_DESPESAS',
} as const;

export type CategoriaMovimentacaoAvulsaType = typeof CATEGORIA_MOVIMENTACAO_AVULSA[keyof typeof CATEGORIA_MOVIMENTACAO_AVULSA];

export const NIVEL_RISCO_VALE = {
    NORMAL: 'NORMAL',
    RISCO_MEDIO: 'RISCO_MEDIO',
    RISCO_ALTO: 'RISCO_ALTO',
    TRATADO_SEGURO: 'TRATADO_SEGURO',
    AJUSTADO_MARGEM_CRITICA: 'AJUSTADO_MARGEM_CRITICA',
} as const;

export type NivelRiscoValeType = typeof NIVEL_RISCO_VALE[keyof typeof NIVEL_RISCO_VALE];

export const CLIENTES_ESPECIAIS = {
    INTERNO: 'INTERNO',
} as const;
