-- --- DATABASE SCHEMA: EMBU EXPRESS ---
-- Initial Consolidated Schema

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS "public";
ALTER SCHEMA "public" OWNER TO "pg_database_owner";
COMMENT ON SCHEMA "public" IS 'standard public schema';

SET default_tablespace = '';
SET default_table_access_method = "heap";

-- --- TABLES ---

-- TABLE: clientes
CREATE TABLE IF NOT EXISTS "public"."clientes" (
    "id" bigint PRIMARY KEY NOT NULL,
    "public_id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "nome_fantasia" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "ativo" boolean DEFAULT true NOT NULL
);
ALTER TABLE "public"."clientes" OWNER TO "postgres";
ALTER TABLE "public"."clientes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."clients_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: unidades_cliente
CREATE TABLE IF NOT EXISTS "public"."unidades_cliente" (
    "id" bigint PRIMARY KEY NOT NULL,
    "cliente_id" bigint NOT NULL,
    "nome_unidade" character varying(255) NOT NULL,
    "razao_social" character varying(255) NOT NULL,
    "cnpj" character varying(20) NOT NULL,
    "cep" character varying(10) NOT NULL,
    "logradouro" character varying(255) NOT NULL,
    "numero" character varying(20) NOT NULL,
    "complemento" character varying(100),
    "bairro" character varying(100) NOT NULL,
    "cidade" character varying(100) NOT NULL,
    "estado" character(2) NOT NULL,
    "km_contratados" integer DEFAULT 0,
    "escala_semanal" integer[] DEFAULT '{}',
    "ativo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."unidades_cliente" OWNER TO "postgres";
ALTER TABLE "public"."unidades_cliente" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."unidades_cliente_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: empresas
CREATE TABLE IF NOT EXISTS "public"."empresas" (
    "id" bigint NOT NULL,
    "nome_fantasia" "text" NOT NULL,
    "razao_social" "text" NOT NULL,
    "cnpj" "text" NOT NULL,
    "ativo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "codigo" "text"
);
ALTER TABLE "public"."empresas" OWNER TO "postgres";
ALTER TABLE "public"."empresas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."empresas_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
COMMENT ON COLUMN "public"."empresas"."codigo" IS 'Sigla da empresa (ex: EE, ES, ED)';

-- TABLE: perfis
CREATE TABLE IF NOT EXISTS "public"."perfis" (
    "id" integer PRIMARY KEY NOT NULL,
    "nome" character varying(50) NOT NULL,
    "descricao" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."perfis" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."roles_id_seq" AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE "public"."roles_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."roles_id_seq" OWNED BY "public"."perfis"."id";
ALTER TABLE ONLY "public"."perfis" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."roles_id_seq"'::"regclass");

-- TABLE: permissoes
CREATE TABLE IF NOT EXISTS "public"."permissoes" (
    "id" integer NOT NULL,
    "nome_interno" character varying(100) NOT NULL,
    "modulo" character varying(100) NOT NULL,
    "descricao" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."permissoes" OWNER TO "postgres";
CREATE SEQUENCE IF NOT EXISTS "public"."permissoes_id_seq" AS integer START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE "public"."permissoes_id_seq" OWNER TO "postgres";
ALTER SEQUENCE "public"."permissoes_id_seq" OWNED BY "public"."permissoes"."id";
ALTER TABLE ONLY "public"."permissoes" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."permissoes_id_seq"'::"regclass");

-- TABLE: perfil_permissoes
CREATE TABLE IF NOT EXISTS "public"."perfil_permissoes" (
    "perfil_id" integer NOT NULL,
    "permissao_id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."perfil_permissoes" OWNER TO "postgres";

-- TABLE: usuarios
CREATE TABLE IF NOT EXISTS "public"."usuarios" (
    "id" "uuid" PRIMARY KEY NOT NULL,
    "perfil_id" integer NOT NULL,
    "nome_completo" character varying(255) NOT NULL,
    "cpf" character varying(14) NOT NULL,
    "email" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "status" character varying(20) DEFAULT 'PENDENTE'::character varying,
    "chave_pix" "text",
    "data_nascimento" "date",
    "rg" "text",
    "nome_mae" "text",
    "endereco_completo" "text",
    "telefone" "text",
    "telefone_recado" "text",

    "cnh_registro" "text",
    "cnh_vencimento" "date",
    "cnh_categoria" "text",
    "cnpj" "text",
    "moto_modelo" "text",
    "moto_cor" "text",
    "moto_ano" "text",
    "moto_placa" "text",
    "senha_padrao" boolean DEFAULT false,
    "tipo_chave_pix" "text",
    "valor_mei" numeric DEFAULT 0
);
ALTER TABLE "public"."usuarios" OWNER TO "postgres";
COMMENT ON COLUMN "public"."usuarios"."senha_padrao" IS 'Indica se o usuário ainda está usando a senha padrão gerada pelo sistema.';

-- TABLE: colaborador_clientes (Turnos/Vínculos)
CREATE TABLE IF NOT EXISTS "public"."colaborador_clientes" (
    "id" bigint NOT NULL,
    "colaborador_id" "uuid" NOT NULL,
    "cliente_id" bigint,
    "unidade_id" bigint,
    "empresa_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "valor_contrato" numeric DEFAULT 0 NOT NULL,
    "valor_aluguel" numeric DEFAULT 0,
    "valor_bonus" numeric DEFAULT 0,
    "ajuda_custo" numeric DEFAULT 0,
    "valor_adiantamento" numeric DEFAULT 0,
    "data_inicio" "date",
    "data_fim" "date"
);
ALTER TABLE "public"."colaborador_clientes" OWNER TO "postgres";
ALTER TABLE "public"."colaborador_clientes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."colaborador_clientes_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
COMMENT ON COLUMN "public"."colaborador_clientes"."valor_aluguel" IS 'Valor do aluguel da moto para este vínculo';

-- TABLE: colaborador_cliente_horarios
CREATE TABLE IF NOT EXISTS "public"."colaborador_cliente_horarios" (
    "id" bigint NOT NULL,
    "colaborador_cliente_id" bigint NOT NULL,
    "dia_semana" integer NOT NULL CHECK ("dia_semana" >= 0 AND "dia_semana" <= 6),
    "hora_inicio" time without time zone NOT NULL,
    "hora_fim" time without time zone NOT NULL,
    "tolerancia_pausa_min" integer DEFAULT 0,
    "created_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."colaborador_cliente_horarios" OWNER TO "postgres";
ALTER TABLE "public"."colaborador_cliente_horarios" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."colaborador_cliente_horarios_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
COMMENT ON COLUMN "public"."colaborador_clientes"."valor_bonus" IS 'Valor de bônus (Zero Falta) para este vínculo';
COMMENT ON COLUMN "public"."colaborador_clientes"."ajuda_custo" IS 'Ajuda de custo para este vínculo';
COMMENT ON COLUMN "public"."colaborador_clientes"."data_fim" IS 'Data de término do vínculo (para pro-rata de desligamento)';

-- TABLE: registros_ponto
CREATE TABLE IF NOT EXISTS "public"."registros_ponto" (
    "id" bigint NOT NULL,
    "usuario_id" "uuid" NOT NULL,
    "data_referencia" "date" NOT NULL,
    "entrada_hora" timestamp with time zone NOT NULL,
    "entrada_km" numeric,
    "saida_hora" timestamp with time zone,
    "saida_km" numeric,
    "status_entrada" character varying(20),
    "status_saida" character varying(20),
    "observacao" "text",
    "criado_por" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "detalhes_calculo" "jsonb" DEFAULT '{}'::jsonb,
    "saldo_minutos" integer DEFAULT 0,
    "cliente_id" bigint,
    "empresa_id" bigint,
    "colaborador_cliente_id" bigint,
    "entrada_loc" "jsonb",
    "saida_loc" "jsonb",
    "entrada_lat" numeric,
    "entrada_lng" numeric,
    "entrada_metadata" jsonb DEFAULT '{}'::jsonb,
    "saida_lat" numeric,
    "saida_lng" numeric,
    "saida_metadata" jsonb DEFAULT '{}'::jsonb,
    "saida_distancia_trabalho" numeric DEFAULT 0
);
ALTER TABLE "public"."registros_ponto" OWNER TO "postgres";
ALTER TABLE "public"."registros_ponto" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."time_records_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);
COMMENT ON COLUMN "public"."registros_ponto"."cliente_id" IS 'Cliente (Turno) vinculado a este registro de atividade';
COMMENT ON COLUMN "public"."registros_ponto"."empresa_id" IS 'Empresa pagadora vinculada a este registro de atividade';
COMMENT ON COLUMN "public"."registros_ponto"."colaborador_cliente_id" IS 'ID do vínculo (turno) específico do colaborador para este registro';
COMMENT ON COLUMN "public"."registros_ponto"."entrada_loc" IS 'Dados de geolocalização capturados no momento da entrada';
COMMENT ON COLUMN "public"."registros_ponto"."saida_loc" IS 'Dados de geolocalização capturados no momento da saída';

-- TABLE: registros_pausas
CREATE TABLE IF NOT EXISTS "public"."registros_pausas" (
    "id" bigint NOT NULL,
    "ponto_id" bigint NOT NULL,
    "inicio_hora" timestamp with time zone NOT NULL,
    "fim_hora" timestamp with time zone,
    "inicio_km" numeric,
    "fim_km" numeric,
    "inicio_loc" "jsonb",
    "fim_loc" "jsonb",
    "inicio_lat" numeric,
    "inicio_lng" numeric,
    "inicio_metadata" jsonb DEFAULT '{}'::jsonb,
    "fim_lat" numeric,
    "fim_lng" numeric,
    "fim_metadata" jsonb DEFAULT '{}'::jsonb,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "distancia_trabalho" numeric DEFAULT 0,
    "distancia_pausa" numeric DEFAULT 0
);
ALTER TABLE "public"."registros_pausas" OWNER TO "postgres";
ALTER TABLE "public"."registros_pausas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."registros_pausas_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: tipos_ocorrencia
CREATE TABLE IF NOT EXISTS "public"."tipos_ocorrencia" (
    "id" integer NOT NULL,
    "descricao" character varying(100) NOT NULL,
    "impacto_financeiro" boolean DEFAULT false,
    "valor_padrao" numeric DEFAULT 0,
    "tipo_lancamento" character varying(10) DEFAULT 'SAIDA'::character varying,
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "tipos_ocorrencia_tipo_lancamento_check" CHECK (("tipo_lancamento" = ANY (ARRAY['ENTRADA'::"text", 'SAIDA'::"text"])))
);
ALTER TABLE "public"."tipos_ocorrencia" OWNER TO "postgres";
ALTER TABLE "public"."tipos_ocorrencia" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."tipos_ocorrencia_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: ocorrencias
CREATE TABLE IF NOT EXISTS "public"."ocorrencias" (
    "id" bigint NOT NULL,
    "colaborador_id" "uuid" NOT NULL,
    "colaborador_cliente_id" bigint,
    "tipo_id" integer NOT NULL,
    "data_ocorrencia" "date" NOT NULL,
    "valor" numeric DEFAULT 0,
    "impacto_financeiro" boolean DEFAULT false,
    "tipo_lancamento" character varying(10) DEFAULT 'SAIDA'::character varying,
    "observacao" "text" NOT NULL,
    "criado_por" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "ocorrencias_tipo_lancamento_check" CHECK (("tipo_lancamento" = ANY (ARRAY['ENTRADA'::"text", 'SAIDA'::"text"])))
);
ALTER TABLE "public"."ocorrencias" OWNER TO "postgres";
ALTER TABLE "public"."ocorrencias" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."ocorrencias_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: feriados
CREATE TABLE IF NOT EXISTS "public"."feriados" (
    "id" bigint NOT NULL,
    "data" "date" NOT NULL,
    "descricao" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "feriados_data_key" UNIQUE ("data")
);
ALTER TABLE "public"."feriados" OWNER TO "postgres";
ALTER TABLE "public"."feriados" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."feriados_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: fechamentos_financeiros
CREATE TABLE IF NOT EXISTS "public"."fechamentos_financeiros" (
    "id" bigint NOT NULL,
    "colaborador_id" "uuid" NOT NULL,
    "mes" integer NOT NULL,
    "ano" integer NOT NULL,
    "resumo_json" "jsonb" NOT NULL,
    "saldo_final" numeric NOT NULL,
    "data_fechamento" timestamp with time zone DEFAULT "now"(),
    "data_pagamento" timestamp with time zone,
    "pago" boolean DEFAULT false,
    "fechado_por" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "fechamentos_financeiros_mes_check" CHECK (mes >= 1 AND mes <= 12)
);
ALTER TABLE "public"."fechamentos_financeiros" OWNER TO "postgres";
ALTER TABLE "public"."fechamentos_financeiros" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."fechamentos_financeiros_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: confirmacoes_adiantamento
CREATE TABLE IF NOT EXISTS "public"."confirmacoes_adiantamento" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "colaborador_id" "uuid" NOT NULL REFERENCES "public"."usuarios"("id") ON DELETE CASCADE,
    "mes" integer NOT NULL CHECK ("mes" >= 1 AND "mes" <= 12),
    "ano" integer NOT NULL,
    "confirmado_por" "uuid" REFERENCES "public"."usuarios"("id") ON DELETE SET NULL,
    "data_confirmacao" timestamp with time zone DEFAULT "now"(),
    "created_at" timestamp with time zone DEFAULT "now"(),
    UNIQUE("colaborador_id", "mes", "ano")
);
ALTER TABLE "public"."confirmacoes_adiantamento" OWNER TO "postgres";
COMMENT ON TABLE "public"."confirmacoes_adiantamento" IS 'Registra a confirmação manual do pagamento de adiantamentos para colaboradores em um determinado mês/ano.';

-- TABLE: configuracoes_sistema
CREATE TABLE IF NOT EXISTS "public"."configuracoes_sistema" (
    "chave" character varying(50) NOT NULL,
    "valor" character varying(255) NOT NULL,
    "descricao" "text",
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."configuracoes_sistema" OWNER TO "postgres";

-- TABLE: app_updates
CREATE TABLE IF NOT EXISTS "public"."app_updates" (
    "id" bigint NOT NULL,
    "platform" "text" NOT NULL,
    "latest_version" character varying(50) NOT NULL,
    "url_zip" "text" NOT NULL,
    "force_update" boolean DEFAULT false NOT NULL,
    "changelog" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "app_updates_platform_check" CHECK (("platform" = ANY (ARRAY['android'::"text", 'ios'::"text"])))
);
ALTER TABLE "public"."app_updates" OWNER TO "postgres";
ALTER TABLE "public"."app_updates" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."app_updates_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- --- CONSTRAINTS & INDEXES ---

CREATE UNIQUE INDEX IF NOT EXISTS "idx_clientes_public_id" ON "public"."clientes" ("public_id");

ALTER TABLE ONLY "public"."unidades_cliente" ADD CONSTRAINT "unidades_cliente_cnpj_key" UNIQUE ("cnpj");
CREATE INDEX IF NOT EXISTS "idx_unidades_cliente_cliente_id" ON "public"."unidades_cliente" ("cliente_id");

ALTER TABLE ONLY "public"."empresas" ADD CONSTRAINT "empresas_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."empresas" ADD CONSTRAINT "empresas_cnpj_key" UNIQUE ("cnpj");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_empresas_codigo" ON "public"."empresas" USING "btree" ("codigo");

ALTER TABLE ONLY "public"."perfis" ADD CONSTRAINT "roles_name_key" UNIQUE ("nome");

ALTER TABLE ONLY "public"."permissoes" ADD CONSTRAINT "permissoes_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."permissoes" ADD CONSTRAINT "permissoes_nome_interno_key" UNIQUE ("nome_interno");

ALTER TABLE ONLY "public"."perfil_permissoes" ADD CONSTRAINT "perfil_permissoes_pkey" PRIMARY KEY ("perfil_id", "permissao_id");

ALTER TABLE ONLY "public"."usuarios" ADD CONSTRAINT "usuarios_cpf_key" UNIQUE ("cpf");
ALTER TABLE ONLY "public"."usuarios" ADD CONSTRAINT "usuarios_email_key" UNIQUE ("email");
ALTER TABLE ONLY "public"."usuarios" ADD CONSTRAINT "usuarios_cnpj_key" UNIQUE ("cnpj");
ALTER TABLE ONLY "public"."usuarios" ADD CONSTRAINT "usuarios_chave_pix_key" UNIQUE ("chave_pix");
CREATE INDEX "idx_usuarios_email" ON "public"."usuarios" USING "btree" ("email");

ALTER TABLE ONLY "public"."colaborador_clientes" ADD CONSTRAINT "colaborador_clientes_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_colaborador_clientes_cliente" ON "public"."colaborador_clientes" USING "btree" ("cliente_id");
CREATE INDEX "idx_colaborador_clientes_unidade" ON "public"."colaborador_clientes" USING "btree" ("unidade_id");
CREATE INDEX "idx_colaborador_clientes_colaborador" ON "public"."colaborador_clientes" USING "btree" ("colaborador_id");
CREATE INDEX "idx_colaborador_clientes_empresa" ON "public"."colaborador_clientes" USING "btree" ("empresa_id");

-- CONSTRAINTS: colaborador_cliente_horarios
ALTER TABLE ONLY "public"."colaborador_cliente_horarios" ADD CONSTRAINT "colaborador_cliente_horarios_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."colaborador_cliente_horarios" ADD CONSTRAINT "fk_horarios_colaborador_cliente" FOREIGN KEY (colaborador_cliente_id) REFERENCES public.colaborador_clientes(id) ON DELETE CASCADE;
CREATE INDEX "idx_horarios_colaborador_cliente" ON "public"."colaborador_cliente_horarios" USING "btree" ("colaborador_cliente_id");

ALTER TABLE ONLY "public"."registros_ponto" ADD CONSTRAINT "time_records_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_registros_ponto_cliente" ON "public"."registros_ponto" USING "btree" ("cliente_id");
CREATE INDEX "idx_registros_ponto_empresa" ON "public"."registros_ponto" USING "btree" ("empresa_id");
CREATE INDEX "idx_registros_ponto_vinculo" ON "public"."registros_ponto" USING "btree" ("colaborador_cliente_id");
CREATE INDEX "idx_registros_ponto_usuario_data" ON "public"."registros_ponto" USING "btree" ("usuario_id", "data_referencia");
CREATE INDEX "idx_registros_ponto_data" ON "public"."registros_ponto" USING "btree" ("data_referencia" DESC);
CREATE INDEX "idx_registros_ponto_status" ON "public"."registros_ponto" USING "btree" ("status_entrada", "status_saida");

ALTER TABLE ONLY "public"."registros_pausas" ADD CONSTRAINT "registros_pausas_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_registros_pausas_ponto" ON "public"."registros_pausas" USING "btree" ("ponto_id");

ALTER TABLE ONLY "public"."tipos_ocorrencia" ADD CONSTRAINT "tipos_ocorrencia_pkey" PRIMARY KEY ("id");
ALTER TABLE ONLY "public"."tipos_ocorrencia" ADD CONSTRAINT "tipos_ocorrencia_descricao_key" UNIQUE ("descricao");

ALTER TABLE ONLY "public"."ocorrencias" ADD CONSTRAINT "ocorrencias_pkey" PRIMARY KEY ("id");
CREATE INDEX "idx_ocorrencias_colaborador" ON "public"."ocorrencias" USING "btree" ("colaborador_id");
CREATE INDEX "idx_ocorrencias_vinculo" ON "public"."ocorrencias" USING "btree" ("colaborador_cliente_id");
CREATE INDEX "idx_ocorrencias_tipo" ON "public"."ocorrencias" USING "btree" ("tipo_id");
CREATE INDEX "idx_ocorrencias_data" ON "public"."ocorrencias" USING "btree" ("data_ocorrencia" DESC);

ALTER TABLE ONLY "public"."feriados" ADD CONSTRAINT "feriados_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."fechamentos_financeiros" ADD CONSTRAINT "fechamentos_financeiros_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."configuracoes_sistema" ADD CONSTRAINT "configuracoes_sistema_pkey" PRIMARY KEY ("chave");

ALTER TABLE ONLY "public"."app_updates" ADD CONSTRAINT "app_updates_pkey" PRIMARY KEY ("id");

-- --- FOREIGN KEYS ---

ALTER TABLE ONLY "public"."usuarios" ADD CONSTRAINT "usuarios_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY "public"."usuarios" ADD CONSTRAINT "usuarios_perfil_id_fkey" FOREIGN KEY ("perfil_id") REFERENCES "public"."perfis"("id") ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."perfil_permissoes" ADD CONSTRAINT "fk_perfil_permissoes_perfil" FOREIGN KEY ("perfil_id") REFERENCES "public"."perfis"("id") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY "public"."perfil_permissoes" ADD CONSTRAINT "fk_perfil_permissoes_permissao" FOREIGN KEY ("permissao_id") REFERENCES "public"."permissoes"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."colaborador_clientes" ADD CONSTRAINT "fk_colaborador_cliente_cliente" FOREIGN KEY ("cliente_id") REFERENCES "public"."clientes"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."colaborador_clientes" ADD CONSTRAINT "fk_colaborador_cliente_unidade" FOREIGN KEY ("unidade_id") REFERENCES "public"."unidades_cliente"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."colaborador_clientes" ADD CONSTRAINT "fk_colaborador_cliente_empresa" FOREIGN KEY ("empresa_id") REFERENCES "public"."empresas"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."colaborador_clientes" ADD CONSTRAINT "fk_colaborador_cliente_usuario" FOREIGN KEY ("colaborador_id") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."registros_ponto" ADD CONSTRAINT "fk_ponto_cliente" FOREIGN KEY ("cliente_id") REFERENCES "public"."clientes"("id") ON DELETE RESTRICT;
ALTER TABLE ONLY "public"."registros_ponto" ADD CONSTRAINT "fk_ponto_empresa" FOREIGN KEY ("empresa_id") REFERENCES "public"."empresas"("id") ON DELETE RESTRICT;
ALTER TABLE ONLY "public"."registros_ponto" ADD CONSTRAINT "fk_ponto_vinculo" FOREIGN KEY ("colaborador_cliente_id") REFERENCES "public"."colaborador_clientes"("id") ON DELETE SET NULL;
ALTER TABLE ONLY "public"."registros_ponto" ADD CONSTRAINT "registros_ponto_criado_por_fkey" FOREIGN KEY ("criado_por") REFERENCES "public"."usuarios"("id") ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ONLY "public"."registros_ponto" ADD CONSTRAINT "registros_ponto_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."registros_pausas" ADD CONSTRAINT "fk_pausa_ponto" FOREIGN KEY ("ponto_id") REFERENCES "public"."registros_ponto"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."ocorrencias" ADD CONSTRAINT "fk_ocorrencia_colaborador" FOREIGN KEY ("colaborador_id") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."ocorrencias" ADD CONSTRAINT "fk_ocorrencia_tipo" FOREIGN KEY ("tipo_id") REFERENCES "public"."tipos_ocorrencia"("id") ON DELETE RESTRICT;
ALTER TABLE ONLY "public"."ocorrencias" ADD CONSTRAINT "fk_ocorrencia_vinculo" FOREIGN KEY ("colaborador_cliente_id") REFERENCES "public"."colaborador_clientes"("id") ON DELETE RESTRICT;
ALTER TABLE ONLY "public"."ocorrencias" ADD CONSTRAINT "fk_ocorrencia_criado_por" FOREIGN KEY ("criado_por") REFERENCES "public"."usuarios"("id") ON DELETE SET NULL;

ALTER TABLE ONLY "public"."fechamentos_financeiros" ADD CONSTRAINT "fk_fechamento_colaborador" FOREIGN KEY ("colaborador_id") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."fechamentos_financeiros" ADD CONSTRAINT "fk_fechamento_fechador" FOREIGN KEY ("fechado_por") REFERENCES "public"."usuarios"("id") ON DELETE SET NULL;

-- --- GRANTS ---

GRANT USAGE ON SCHEMA "public" TO "postgres", "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."clientes" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."unidades_cliente" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."unidades_cliente_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."empresas" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."usuarios" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."colaborador_clientes" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."colaborador_clientes_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."registros_ponto" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."time_records_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."registros_pausas" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."registros_pausas_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."ocorrencias" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."ocorrencias_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."tipos_ocorrencia" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."tipos_ocorrencia_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."feriados" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."feriados_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."fechamentos_financeiros" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."fechamentos_financeiros_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."colaborador_cliente_horarios" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."colaborador_cliente_horarios_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."confirmacoes_adiantamento" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."configuracoes_sistema" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."app_updates" TO "service_role";
GRANT ALL ON SEQUENCE "public"."app_updates_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."perfis" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."permissoes" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."permissoes_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."perfil_permissoes" TO "anon", "authenticated", "service_role";

-- --- STORAGE CONFIGURATION ---
INSERT INTO storage.buckets (id, name, public) VALUES ('ota', 'ota', true) ON CONFLICT (id) DO NOTHING;

-- --- PERMISSIONS SEED (Essentials) ---
-- (Aqui você pode incluir os INSERTs de permissões e perfis iniciais se desejar)

-- --- SEQUENCE SYNC ---
-- Sincroniza sequences após inserções manuais iniciais (se houver)
SELECT setval('public.roles_id_seq', COALESCE((SELECT MAX(id) FROM public.perfis), 1));
SELECT setval('public.permissoes_id_seq', COALESCE((SELECT MAX(id) FROM public.permissoes), 1));
SELECT setval('public.tipos_ocorrencia_id_seq', COALESCE((SELECT MAX(id) FROM public.tipos_ocorrencia), 1));
