-- Create table for advance payment confirmations
CREATE TABLE IF NOT EXISTS public.confirmacoes_adiantamento (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    colaborador_id uuid NOT NULL REFERENCES public.usuarios(id) ON DELETE CASCADE,
    mes integer NOT NULL CHECK (mes >= 1 AND mes <= 12),
    ano integer NOT NULL,
    confirmado_por uuid REFERENCES public.usuarios(id) ON DELETE SET NULL,
    data_confirmacao timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now(),
    UNIQUE(colaborador_id, mes, ano)
);

-- Add comments for documentation
COMMENT ON TABLE public.confirmacoes_adiantamento IS 'Registra a confirmação manual do pagamento de adiantamentos para colaboradores em um determinado mês/ano.';
COMMENT ON COLUMN public.confirmacoes_adiantamento.colaborador_id IS 'ID do colaborador que recebeu o adiantamento.';
COMMENT ON COLUMN public.confirmacoes_adiantamento.confirmado_por IS 'ID do administrador que confirmou o pagamento.';

-- Grant permissions
GRANT ALL ON TABLE public.confirmacoes_adiantamento TO anon;
GRANT ALL ON TABLE public.confirmacoes_adiantamento TO authenticated;
GRANT ALL ON TABLE public.confirmacoes_adiantamento TO service_role;
