-- Migration: Refactor Collaborator and Add Pauses
-- Date: 2026-01-31

-- 1. Create table `colaborador_clientes`
CREATE TABLE IF NOT EXISTS public.colaborador_clientes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colaborador_id uuid NOT NULL,
    cliente_id bigint NOT NULL,
    empresa_id bigint NOT NULL, -- Empresa responsavel pelo contrato neste horario
    hora_inicio time NOT NULL, -- Format HH:mm:ss
    hora_fim time NOT NULL,   -- Format HH:mm:ss
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    
    -- Explicit Constraints for better naming and management
    CONSTRAINT fk_colaborador_cliente_usuario FOREIGN KEY (colaborador_id) REFERENCES public.usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_colaborador_cliente_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_colaborador_cliente_empresa FOREIGN KEY (empresa_id) REFERENCES public.empresas(id) ON DELETE CASCADE
);

-- Indexes for FKs (Performance & Integrity)
CREATE INDEX IF NOT EXISTS idx_colaborador_clientes_colaborador ON public.colaborador_clientes(colaborador_id);
CREATE INDEX IF NOT EXISTS idx_colaborador_clientes_cliente ON public.colaborador_clientes(cliente_id);
CREATE INDEX IF NOT EXISTS idx_colaborador_clientes_empresa ON public.colaborador_clientes(empresa_id);

-- 2. Create table `registros_pausas`
CREATE TABLE IF NOT EXISTS public.registros_pausas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ponto_id bigint NOT NULL,
    inicio_hora timestamp with time zone NOT NULL,
    fim_hora timestamp with time zone,
    inicio_km integer,
    fim_km integer,
    inicio_loc jsonb,
    fim_loc jsonb,
    remunerada boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),

    -- Explicit Constraints
    CONSTRAINT fk_pausa_ponto FOREIGN KEY (ponto_id) REFERENCES public.registros_ponto(id) ON DELETE CASCADE
);

-- Indexes for FKs
CREATE INDEX IF NOT EXISTS idx_registros_pausas_ponto ON public.registros_pausas(ponto_id);

-- 3. Cleanup Legacy Structures (CAUTION: Destructive changes)
-- Drop the old table linking users to shifts directly
DROP TABLE IF EXISTS public.usuario_turnos;

-- Drop columns from usuarios that are no longer single-value
-- We use ALTER TABLE to drop columns.
ALTER TABLE public.usuarios 
DROP COLUMN IF EXISTS cliente_id,
DROP COLUMN IF EXISTS empresa_id;
