-- TABLE: categoria_itens (Categorias dinâmicas criadas pelo usuário)
CREATE TABLE IF NOT EXISTS "public"."categoria_itens" (
    "id" bigint PRIMARY KEY NOT NULL,
    "nome" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."categoria_itens" OWNER TO "postgres";
ALTER TABLE "public"."categoria_itens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."categoria_itens_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: itens_equipamentos (Catálogo de Itens)
CREATE TABLE IF NOT EXISTS "public"."itens_equipamentos" (
    "id" bigint PRIMARY KEY NOT NULL,
    "nome" character varying(255) NOT NULL,
    "categoria_id" bigint NOT NULL,
    "ativo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."itens_equipamentos" OWNER TO "postgres";
ALTER TABLE "public"."itens_equipamentos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."itens_equipamentos_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- TABLE: colaborador_itens (Alocações)
CREATE TABLE IF NOT EXISTS "public"."colaborador_itens" (
    "id" bigint PRIMARY KEY NOT NULL,
    "colaborador_id" uuid NOT NULL,
    "item_id" bigint NOT NULL,
    "quantidade" integer DEFAULT 1 NOT NULL,
    "observacao" text,
    "criado_por" uuid,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"()
);
ALTER TABLE "public"."colaborador_itens" OWNER TO "postgres";
ALTER TABLE "public"."colaborador_itens" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."colaborador_itens_id_seq" START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1);

-- CONSTRAINTS & INDEXES
ALTER TABLE ONLY "public"."itens_equipamentos" ADD CONSTRAINT "fk_itens_equipamentos_categoria" FOREIGN KEY ("categoria_id") REFERENCES "public"."categoria_itens"("id") ON DELETE RESTRICT;

ALTER TABLE ONLY "public"."colaborador_itens" ADD CONSTRAINT "fk_colaborador_itens_usuario" FOREIGN KEY ("colaborador_id") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE;
ALTER TABLE ONLY "public"."colaborador_itens" ADD CONSTRAINT "fk_colaborador_itens_item" FOREIGN KEY ("item_id") REFERENCES "public"."itens_equipamentos"("id") ON DELETE RESTRICT;
ALTER TABLE ONLY "public"."colaborador_itens" ADD CONSTRAINT "fk_colaborador_itens_criador" FOREIGN KEY ("criado_por") REFERENCES "public"."usuarios"("id") ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS "idx_itens_equipamentos_categoria" ON "public"."itens_equipamentos" USING "btree" ("categoria_id");
CREATE INDEX IF NOT EXISTS "idx_colaborador_itens_usuario" ON "public"."colaborador_itens" USING "btree" ("colaborador_id");
CREATE INDEX IF NOT EXISTS "idx_colaborador_itens_item" ON "public"."colaborador_itens" USING "btree" ("item_id");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_categoria_itens_nome_unique_lower" ON "public"."categoria_itens" (LOWER(nome));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_itens_equipamentos_nome_unique_lower" ON "public"."itens_equipamentos" (LOWER(nome));

-- GRANTS
GRANT ALL ON TABLE "public"."categoria_itens" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."categoria_itens_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."itens_equipamentos" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."itens_equipamentos_id_seq" TO "anon", "authenticated", "service_role";

GRANT ALL ON TABLE "public"."colaborador_itens" TO "anon", "authenticated", "service_role";
GRANT ALL ON SEQUENCE "public"."colaborador_itens_id_seq" TO "anon", "authenticated", "service_role";

-- 6. INITIAL SYSTEM PERMISSIONS FOR EQUIPAMENTOS (MULTI-ENVIRONMENT SAFE)
INSERT INTO "public"."permissoes" ("nome_interno", "modulo", "descricao") VALUES
('equipamentos:ver', 'Equipamentos', 'Visualizar catálogo e alocações de equipamentos'),
('equipamentos:editar', 'Equipamentos', 'Cadastrar, editar e excluir itens/categorias e alocar')
ON CONFLICT (nome_interno) DO UPDATE SET 
    modulo = EXCLUDED.modulo,
    descricao = EXCLUDED.descricao;

-- ASSOCIATE TO SUPER_ADMIN AND CEO PROFILE DINAMICALLY
INSERT INTO "public"."perfil_permissoes" ("perfil_id", "permissao_id")
SELECT p.id as perfil_id, perm.id as permissao_id
FROM "public"."perfis" p
CROSS JOIN "public"."permissoes" perm
WHERE p.nome IN ('super_admin', 'ceo')
  AND perm.nome_interno IN ('equipamentos:ver', 'equipamentos:editar')
ON CONFLICT DO NOTHING;

-- SYNC SEQUENCES AVOID CONFLICTS
SELECT setval('public.permissoes_id_seq', (SELECT MAX(id) FROM public.permissoes));
