


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."clientes" (
    "id" bigint NOT NULL,
    "nome_fantasia" character varying(255) NOT NULL,
    "razao_social" character varying(255) NOT NULL,
    "cnpj" character varying(20) NOT NULL,
    "cep" character varying(10) NOT NULL,
    "logradouro" character varying(255) NOT NULL,
    "numero" character varying(20) NOT NULL,
    "complemento" character varying(100),
    "bairro" character varying(100) NOT NULL,
    "cidade" character varying(100) NOT NULL,
    "estado" character(2) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "ativo" boolean DEFAULT true NOT NULL
);


ALTER TABLE "public"."clientes" OWNER TO "postgres";


ALTER TABLE "public"."clientes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."colaborador_clientes" (
    "id" bigint NOT NULL,
    "colaborador_id" "uuid" NOT NULL,
    "cliente_id" bigint NOT NULL,
    "empresa_id" bigint NOT NULL,
    "hora_inicio" time without time zone NOT NULL,
    "hora_fim" time without time zone NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "valor_contrato" numeric DEFAULT 0,
    "valor_aluguel" numeric DEFAULT 0,
    "valor_bonus" numeric DEFAULT 0,
    "ajuda_custo" numeric DEFAULT 0,
    "mei" boolean DEFAULT false
);


ALTER TABLE "public"."colaborador_clientes" OWNER TO "postgres";


COMMENT ON COLUMN "public"."colaborador_clientes"."valor_contrato" IS 'Valor do contrato para este vínculo específico';



COMMENT ON COLUMN "public"."colaborador_clientes"."valor_aluguel" IS 'Valor do aluguel da moto para este vínculo';



COMMENT ON COLUMN "public"."colaborador_clientes"."valor_bonus" IS 'Valor de bônus (Zero Falta) para este vínculo';



COMMENT ON COLUMN "public"."colaborador_clientes"."ajuda_custo" IS 'Ajuda de custo para este vínculo';



COMMENT ON COLUMN "public"."colaborador_clientes"."mei" IS 'Se é contrato MEI neste vínculo';



ALTER TABLE "public"."colaborador_clientes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."colaborador_clientes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."configuracoes_sistema" (
    "chave" character varying(50) NOT NULL,
    "valor" character varying(255) NOT NULL,
    "descricao" "text",
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."configuracoes_sistema" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."empresas" (
    "id" bigint NOT NULL,
    "nome_fantasia" "text" NOT NULL,
    "razao_social" "text" NOT NULL,
    "cnpj" "text" NOT NULL,
    "ativo" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL,
    "codigo" "text"
);


ALTER TABLE "public"."empresas" OWNER TO "postgres";


COMMENT ON COLUMN "public"."empresas"."codigo" IS 'Sigla da empresa (ex: EE, ES, ED)';



ALTER TABLE "public"."empresas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."empresas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."perfis" (
    "id" integer NOT NULL,
    "nome" character varying(50) NOT NULL,
    "descricao" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."perfis" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."registros_pausas" (
    "id" bigint NOT NULL,
    "ponto_id" bigint NOT NULL,
    "inicio_hora" timestamp with time zone NOT NULL,
    "fim_hora" timestamp with time zone,
    "inicio_km" integer,
    "fim_km" integer,
    "inicio_loc" "jsonb",
    "fim_loc" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."registros_pausas" OWNER TO "postgres";


ALTER TABLE "public"."registros_pausas" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."registros_pausas_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."registros_ponto" (
    "id" bigint NOT NULL,
    "usuario_id" "uuid" NOT NULL,
    "data_referencia" "date" NOT NULL,
    "entrada_hora" timestamp with time zone NOT NULL,
    "entrada_km" integer,
    "saida_hora" timestamp with time zone,
    "saida_km" integer,
    "status_entrada" character varying(20),
    "status_saida" character varying(20),
    "observacao" "text",
    "criado_por" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "detalhes_calculo" "jsonb" DEFAULT '{}'::"jsonb",
    "saldo_minutos" integer DEFAULT 0,
    "cliente_id" bigint,
    "empresa_id" bigint,
    "entrada_loc" "jsonb",
    "saida_loc" "jsonb"
);


ALTER TABLE "public"."registros_ponto" OWNER TO "postgres";


COMMENT ON COLUMN "public"."registros_ponto"."cliente_id" IS 'Cliente (Turno) vinculado a este registro de ponto';



COMMENT ON COLUMN "public"."registros_ponto"."empresa_id" IS 'Empresa pagadora vinculada a este registro de ponto';



COMMENT ON COLUMN "public"."registros_ponto"."entrada_loc" IS 'Dados de geolocalização capturados no momento da entrada';



COMMENT ON COLUMN "public"."registros_ponto"."saida_loc" IS 'Dados de geolocalização capturados no momento da saída';



CREATE SEQUENCE IF NOT EXISTS "public"."roles_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."roles_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."roles_id_seq" OWNED BY "public"."perfis"."id";



ALTER TABLE "public"."registros_ponto" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."time_records_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."usuarios" (
    "id" "uuid" NOT NULL,
    "perfil_id" integer NOT NULL,
    "nome_completo" character varying(255) NOT NULL,
    "cpf" character varying(14),
    "email" character varying(255) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "status" character varying(20) DEFAULT 'PENDENTE'::character varying,
    "chave_pix" "text",
    "data_nascimento" "date",
    "rg" "text",
    "nome_mae" "text",
    "endereco_completo" "text",
    "telefone" "text",
    "telefone_recado" "text",
    "data_inicio" "date",
    "cnh_registro" "text",
    "cnh_vencimento" "date",
    "cnh_categoria" "text",
    "cnpj" "text",
    "moto_modelo" "text",
    "moto_cor" "text",
    "moto_ano" "text",
    "moto_placa" "text",
    "nome_operacao" "text",
    "empresa_financeiro_id" bigint,
    "valor_ajuda_custo" numeric(10,2) DEFAULT 0,
    "senha_padrao" boolean DEFAULT false
);


ALTER TABLE "public"."usuarios" OWNER TO "postgres";


COMMENT ON COLUMN "public"."usuarios"."senha_padrao" IS 'Indica se o usuário ainda está usando a senha padrão gerada pelo sistema.';



ALTER TABLE ONLY "public"."perfis" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."roles_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."clientes"
    ADD CONSTRAINT "clients_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."colaborador_clientes"
    ADD CONSTRAINT "colaborador_clientes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."configuracoes_sistema"
    ADD CONSTRAINT "configuracoes_sistema_pkey" PRIMARY KEY ("chave");



ALTER TABLE ONLY "public"."empresas"
    ADD CONSTRAINT "empresas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "profiles_cpf_key" UNIQUE ("cpf");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."registros_pausas"
    ADD CONSTRAINT "registros_pausas_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."perfis"
    ADD CONSTRAINT "roles_name_key" UNIQUE ("nome");



ALTER TABLE ONLY "public"."perfis"
    ADD CONSTRAINT "roles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."registros_ponto"
    ADD CONSTRAINT "time_records_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_colaborador_clientes_cliente" ON "public"."colaborador_clientes" USING "btree" ("cliente_id");



CREATE INDEX "idx_colaborador_clientes_colaborador" ON "public"."colaborador_clientes" USING "btree" ("colaborador_id");



CREATE INDEX "idx_colaborador_clientes_empresa" ON "public"."colaborador_clientes" USING "btree" ("empresa_id");



CREATE UNIQUE INDEX "idx_empresas_codigo" ON "public"."empresas" USING "btree" ("codigo");



CREATE INDEX "idx_registros_pausas_ponto" ON "public"."registros_pausas" USING "btree" ("ponto_id");



CREATE INDEX "idx_registros_ponto_cliente" ON "public"."registros_ponto" USING "btree" ("cliente_id");



CREATE INDEX "idx_registros_ponto_empresa" ON "public"."registros_ponto" USING "btree" ("empresa_id");


-- Optimization Indices
CREATE INDEX "idx_usuarios_email" ON "public"."usuarios" USING "btree" ("email");
CREATE INDEX "idx_registros_ponto_usuario_data" ON "public"."registros_ponto" USING "btree" ("usuario_id", "data_referencia");
CREATE INDEX "idx_registros_ponto_data" ON "public"."registros_ponto" USING "btree" ("data_referencia" DESC);
CREATE INDEX "idx_registros_ponto_status" ON "public"."registros_ponto" USING "btree" ("status_entrada", "status_saida");



ALTER TABLE ONLY "public"."colaborador_clientes"
    ADD CONSTRAINT "fk_colaborador_cliente_cliente" FOREIGN KEY ("cliente_id") REFERENCES "public"."clientes"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."colaborador_clientes"
    ADD CONSTRAINT "fk_colaborador_cliente_empresa" FOREIGN KEY ("empresa_id") REFERENCES "public"."empresas"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."colaborador_clientes"
    ADD CONSTRAINT "fk_colaborador_cliente_usuario" FOREIGN KEY ("colaborador_id") REFERENCES "public"."usuarios"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."registros_pausas"
    ADD CONSTRAINT "fk_pausa_ponto" FOREIGN KEY ("ponto_id") REFERENCES "public"."registros_ponto"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."registros_ponto"
    ADD CONSTRAINT "fk_ponto_cliente" FOREIGN KEY ("cliente_id") REFERENCES "public"."clientes"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."registros_ponto"
    ADD CONSTRAINT "fk_ponto_empresa" FOREIGN KEY ("empresa_id") REFERENCES "public"."empresas"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."registros_ponto"
    ADD CONSTRAINT "registros_ponto_criado_por_fkey" FOREIGN KEY ("criado_por") REFERENCES "public"."usuarios"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."registros_ponto"
    ADD CONSTRAINT "registros_ponto_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "public"."usuarios"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_empresa_financeiro_id_fkey" FOREIGN KEY ("empresa_financeiro_id") REFERENCES "public"."empresas"("id");



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."usuarios"
    ADD CONSTRAINT "usuarios_perfil_id_fkey" FOREIGN KEY ("perfil_id") REFERENCES "public"."perfis"("id") ON UPDATE CASCADE ON DELETE RESTRICT;



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."clientes" TO "anon";
GRANT ALL ON TABLE "public"."clientes" TO "authenticated";
GRANT ALL ON TABLE "public"."clientes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."colaborador_clientes" TO "anon";
GRANT ALL ON TABLE "public"."colaborador_clientes" TO "authenticated";
GRANT ALL ON TABLE "public"."colaborador_clientes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."colaborador_clientes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."colaborador_clientes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."colaborador_clientes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."configuracoes_sistema" TO "anon";
GRANT ALL ON TABLE "public"."configuracoes_sistema" TO "authenticated";
GRANT ALL ON TABLE "public"."configuracoes_sistema" TO "service_role";



GRANT ALL ON TABLE "public"."empresas" TO "anon";
GRANT ALL ON TABLE "public"."empresas" TO "authenticated";
GRANT ALL ON TABLE "public"."empresas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."empresas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."perfis" TO "anon";
GRANT ALL ON TABLE "public"."perfis" TO "authenticated";
GRANT ALL ON TABLE "public"."perfis" TO "service_role";



GRANT ALL ON TABLE "public"."registros_pausas" TO "anon";
GRANT ALL ON TABLE "public"."registros_pausas" TO "authenticated";
GRANT ALL ON TABLE "public"."registros_pausas" TO "service_role";



GRANT ALL ON SEQUENCE "public"."registros_pausas_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."registros_pausas_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."registros_pausas_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."registros_ponto" TO "anon";
GRANT ALL ON TABLE "public"."registros_ponto" TO "authenticated";
GRANT ALL ON TABLE "public"."registros_ponto" TO "service_role";



GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."roles_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."time_records_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."time_records_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."time_records_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."usuarios" TO "anon";
GRANT ALL ON TABLE "public"."usuarios" TO "authenticated";
GRANT ALL ON TABLE "public"."usuarios" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";


-- AUTOMATION: Automate updated_at updates
CREATE OR REPLACE FUNCTION "public"."handle_updated_at"()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER "tr_usuarios_updated_at" BEFORE UPDATE ON "public"."usuarios" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();
CREATE TRIGGER "tr_registros_ponto_updated_at" BEFORE UPDATE ON "public"."registros_ponto" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();
CREATE TRIGGER "tr_colaborador_clientes_updated_at" BEFORE UPDATE ON "public"."colaborador_clientes" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();
CREATE TRIGGER "tr_empresas_updated_at" BEFORE UPDATE ON "public"."empresas" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();
CREATE TRIGGER "tr_clientes_updated_at" BEFORE UPDATE ON "public"."clientes" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();
CREATE TRIGGER "tr_registros_pausas_updated_at" BEFORE UPDATE ON "public"."registros_pausas" FOR EACH ROW EXECUTE FUNCTION "public"."handle_updated_at"();







